#!/usr/bin/env python3

from __future__ import annotations

from datetime import datetime, timezone
import os
from pathlib import Path
import xml.etree.ElementTree as ET


CAVE_OUTPUT_DIR = Path(os.environ.get("CAVE_OUTPUT_DIR", "cave_env"))
HEXAPOD_MODEL_PATH = Path(
    os.environ.get("HEXAPOD_MODEL_PATH", "/vendor_rl/models/hexapod_static.xml")
)
CAVE_XML_PATH = CAVE_OUTPUT_DIR / "cave_maze.xml"
OUTPUT_XML_PATH = CAVE_OUTPUT_DIR / "cave_hexapod.xml"


def require_child(parent: ET.Element, tag: str, source: Path) -> ET.Element:
    child = parent.find(tag)
    if child is None:
        raise ValueError(f"{source} is missing <{tag}>")
    return child


def remove_direct_child(parent: ET.Element, child: ET.Element | None) -> None:
    if child is not None:
        parent.remove(child)


def remove_world_body(worldbody: ET.Element, name: str) -> None:
    for body in list(worldbody.findall("body")):
        if body.get("name") == name:
            worldbody.remove(body)
            return
    raise ValueError(f"cave scene is missing worldbody body {name!r}")


def rewrite_cave_mesh_paths(asset: ET.Element) -> None:
    for mesh in asset.findall("mesh"):
        file_attr = mesh.get("file")
        if not file_attr:
            continue
        if "/" not in file_attr:
            mesh.set("file", f"meshes/{file_attr}")


def append_hexapod_mesh_assets(cave_asset: ET.Element, hexapod_asset: ET.Element) -> None:
    for mesh in hexapod_asset.findall("mesh"):
        file_attr = mesh.get("file")
        if not file_attr:
            raise ValueError(f"hexapod mesh {mesh.get('name')!r} is missing file")
        mesh.set("file", f"../rl/STLFILES/{Path(file_attr).name}")
        cave_asset.append(mesh)


def find_hexapod_body(hexapod_worldbody: ET.Element) -> ET.Element:
    for body in hexapod_worldbody.findall("body"):
        if body.get("name") == "hexapod":
            return body
    raise ValueError("hexapod model is missing worldbody body 'hexapod'")


def ensure_root_freejoint(hexapod_body: ET.Element) -> None:
    for child in list(hexapod_body):
        if child.tag == "freejoint":
            child.set("name", "hexapod_root")
            return
        if child.tag == "joint" and child.get("type") == "free":
            child.set("name", "hexapod_root")
            return

    hexapod_body.insert(0, ET.Element("freejoint", {"name": "hexapod_root"}))


def ensure_robot_pov_camera(hexapod_body: ET.Element) -> None:
    for child in hexapod_body.findall("camera"):
        if child.get("name") == "robot_pov":
            return

    insert_index = (
        1 if len(hexapod_body) > 0 and hexapod_body[0].tag == "freejoint" else 0
    )
    hexapod_body.insert(
        insert_index,
        ET.Element(
            "camera",
            {
                "name": "robot_pov",
                "mode": "fixed",
                "pos": "0 0 0.65",
                "xyaxes": "0.7071 -0.7071 0 0.2357 0.2357 0.9428",
            },
        ),
    )


def build() -> None:
    if not CAVE_XML_PATH.exists():
        raise FileNotFoundError(f"cave scene not found: {CAVE_XML_PATH}")
    if not HEXAPOD_MODEL_PATH.exists():
        raise FileNotFoundError(f"hexapod model not found: {HEXAPOD_MODEL_PATH}")

    cave_tree = ET.parse(CAVE_XML_PATH)
    cave_root = cave_tree.getroot()
    hexapod_root = ET.parse(HEXAPOD_MODEL_PATH).getroot()

    cave_compiler = require_child(cave_root, "compiler", CAVE_XML_PATH)
    cave_compiler.attrib.pop("meshdir", None)

    cave_asset = require_child(cave_root, "asset", CAVE_XML_PATH)
    cave_worldbody = require_child(cave_root, "worldbody", CAVE_XML_PATH)
    hexapod_asset = require_child(hexapod_root, "asset", HEXAPOD_MODEL_PATH)
    hexapod_worldbody = require_child(hexapod_root, "worldbody", HEXAPOD_MODEL_PATH)
    hexapod_actuator = require_child(hexapod_root, "actuator", HEXAPOD_MODEL_PATH)

    rewrite_cave_mesh_paths(cave_asset)
    remove_world_body(cave_worldbody, "robot")
    remove_direct_child(cave_root, cave_root.find("sensor"))
    remove_direct_child(cave_root, cave_root.find("keyframe"))

    append_hexapod_mesh_assets(cave_asset, hexapod_asset)

    hexapod_body = find_hexapod_body(hexapod_worldbody)
    ensure_root_freejoint(hexapod_body)
    ensure_robot_pov_camera(hexapod_body)
    hexapod_body.set("pos", "0 2.5 0.065")
    cave_worldbody.append(hexapod_body)
    cave_root.append(hexapod_actuator)

    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    cave_root.insert(
        0,
        ET.Comment(
            f" Generated by build_cave_hexapod.py at {generated_at}; "
            f"sources: {CAVE_XML_PATH.name} + {HEXAPOD_MODEL_PATH.name} "
        ),
    )

    ET.indent(cave_tree, space="  ")
    tmp_path = OUTPUT_XML_PATH.with_suffix(OUTPUT_XML_PATH.suffix + ".tmp")
    cave_tree.write(tmp_path, encoding="utf-8", xml_declaration=True)
    os.replace(tmp_path, OUTPUT_XML_PATH)
    print(f"  Merged cave hexapod XML: {OUTPUT_XML_PATH}")


if __name__ == "__main__":
    build()
